    CMD(BEGIN, 64)    
    CMD(POP, 65)    
    CMD_COMPLEX(PUSH, 66)    
    CMD(MUL, 67)
    CMD(DIV, 68)
    CMD(ADD, 69)
    CMD(SUB, 70)
    CMD(END, 71)

    CMD_REG(R_PUSH, REG_NAME, 73)
    CMD_REG(R_POP, REG_NAME, 72)
   
  
    CMD(SQRT, 73)
    CMD(SIN, 74)
    CMD(COS, 75)
    CMD(TAN, 76)
    CMD(OUT, 77)
    CMD(IN, 78)
    
    CMD_JMP(JMP, 79)
    CMD_JMP(JA, 80)
    CMD_JMP(JB, 81)
    CMD_JMP(JE, 82)
    CMD_JMP(JAE, 83)
    CMD_JMP(JBE, 84)
    CMD_JMP(JNE, 85)
    CMD_JMP(CALL, 86)
    CMD(CUR, 87)

    //CMD_MEM(PUSHMEM, 74)
   //CMD_MEM(POPMEM, 75)
